# Generated by Django 4.2.4 on 2023-08-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='speaker_photos/'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='speaker_photos/'),
        ),
    ]
