# Generated by Django 4.2.4 on 2023-08-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_event_image_speaker_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='photo',
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='photo_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
